#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/xionghao/fvm/versions/3.27.1"
export "FLUTTER_APPLICATION_PATH=/Users/xionghao/Documents/plaud/GitHub/flutter-ble"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/xionghao/Documents/plaud/GitHub/flutter-ble/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=2.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "CONFIGURATION_BUILD_DIR=/Users/xionghao/Documents/plaud/GitHub/flutter-ble/build/ios/iphoneos"
export "DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz1mYWxzZQ=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/xionghao/Documents/plaud/GitHub/flutter-ble/.dart_tool/package_config.json"
